"""Realistic demo data for development and screenshots (``python -m app.cli seed-demo``).

Everything goes through the real services with an injected clock, so wallets, the ledger and the
transaction history stay consistent (``python -m app.cli reconcile`` passes). Demo users carry Telegram
ids >= ``DEMO_BASE`` so they can be removed again with ``seed-demo --purge``.
"""

from __future__ import annotations

import datetime as dt
import io
import random
from decimal import Decimal

from PIL import Image, ImageDraw
from sqlalchemy import delete, select, text, update

from app import timeutil
from app.config import get_settings
from app.db import dispose_engine, session_scope
from app.enums import DisputeResolution
from app.models import (
    AuditLog,
    Broadcast,
    Deposit,
    DepositAddress,
    Dispute,
    LedgerEntry,
    Outbox,
    ScannerSlot,
    SlotNotification,
    TaskSession,
    TransactionHistory,
    User,
    Wallet,
    Withdrawal,
)
from app.services import disputes, payments, proofs, sessions, users, wallet

DEMO_BASE = 9_000_000_000
URL = "https://chatgpt.com/checkout/openai_llc/cs_live_demo{n:04d}#fidDEMO"

SELLERS = [
    ("Liam Carter", "GB", "Europe/London"),
    ("Sofia Rossi", "DE", "Europe/Berlin"),
    ("Mateo Silva", "BR", "America/Sao_Paulo"),
    ("Emma Johnson", "US", "America/New_York"),
    ("Can Yilmaz", "TR", "Europe/Istanbul"),
    ("Chidi Okafor", "NG", "Africa/Lagos"),
    ("Maria Santos", "PH", "Asia/Manila"),
    ("Budi Hartono", "ID", "Asia/Jakarta"),
]
SCANNERS = [  # name, country, tz, alias, reputation, fixed slots
    ("Arjun Mehta", "IN", "Asia/Kolkata", "user1", 92, [(8, 10), (10, 12), (14, 16), (20, 22)]),
    ("Priya Nair", "IN", "Asia/Kolkata", "user2", 74, [(6, 8), (12, 14), (18, 20)]),
    ("Hamza Ali", "PK", "Asia/Karachi", "user3", 66, [(8, 10), (16, 18), (22, 0)]),
    ("Nusrat Jahan", "BD", "Asia/Dhaka", "user4", 55, [(10, 12), (20, 22)]),
    ("Omar Hassan", "EG", "Africa/Cairo", "user5", 48, [(0, 2), (14, 16)]),
    ("Linh Tran", "VN", "Asia/Ho_Chi_Minh", "user6", 83, [(6, 8), (8, 10), (18, 20)]),
]


def mock_screenshot(headline: str, ok: bool = True) -> bytes:
    """A fake browser screenshot (just enough to exercise the proof viewer)."""
    img = Image.new("RGB", (960, 600), (247, 247, 248))
    d = ImageDraw.Draw(img)
    d.rectangle((0, 0, 960, 46), fill=(228, 230, 235))
    d.rounded_rectangle((120, 10, 840, 36), radius=12, fill=(255, 255, 255))
    d.text((140, 16), "https://chatgpt.com/checkout/success", fill=(70, 70, 70))
    d.rounded_rectangle((300, 150, 660, 430), radius=18, fill=(255, 255, 255), outline=(215, 215, 220))
    d.ellipse((450, 180, 510, 240), fill=(16, 163, 127) if ok else (214, 69, 65))
    d.text((340, 270), headline, fill=(30, 30, 30))
    d.text((340, 300), "DEMO SCREENSHOT - generated by seed-demo", fill=(130, 130, 130))
    d.rounded_rectangle((380, 360, 580, 395), radius=8, fill=(16, 163, 127) if ok else (150, 150, 150))
    buffer = io.BytesIO()
    img.save(buffer, "PNG")
    return buffer.getvalue()


async def purge() -> None:
    async with session_scope() as db:
        ids = list((await db.execute(select(User.user_id).where(User.telegram_id >= DEMO_BASE))).scalars())
        if not ids:
            return
        session_ids = list(
            (await db.execute(select(TaskSession.session_id).where(TaskSession.seller_id.in_(ids) | TaskSession.scanner_id.in_(ids)))).scalars()
        )
        withdrawal_ids = list((await db.execute(select(Withdrawal.id).where(Withdrawal.user_id.in_(ids)))).scalars())
        if session_ids:
            await db.execute(delete(Dispute).where(Dispute.session_id.in_(session_ids)))
            await db.execute(delete(TransactionHistory).where(TransactionHistory.session_id.in_(session_ids)))
            await db.execute(delete(LedgerEntry).where(LedgerEntry.ref_type == "session", LedgerEntry.ref_id.in_(session_ids)))
        if withdrawal_ids:
            await db.execute(delete(LedgerEntry).where(LedgerEntry.ref_type == "withdrawal", LedgerEntry.ref_id.in_(withdrawal_ids)))
        deposit_ids = list((await db.execute(select(Deposit.id).where(Deposit.user_id.in_(ids)))).scalars())
        if deposit_ids:
            await db.execute(delete(LedgerEntry).where(LedgerEntry.ref_type == "deposit", LedgerEntry.ref_id.in_(deposit_ids)))
        await db.execute(delete(LedgerEntry).where(LedgerEntry.user_id.in_(ids)))
        if session_ids:
            await db.execute(delete(TaskSession).where(TaskSession.session_id.in_(session_ids)))
        await db.execute(delete(Withdrawal).where(Withdrawal.user_id.in_(ids)))
        await db.execute(delete(Deposit).where(Deposit.user_id.in_(ids)))
        await db.execute(delete(SlotNotification).where(SlotNotification.user_id.in_(ids)))
        await db.execute(delete(ScannerSlot).where(ScannerSlot.user_id.in_(ids)))
        await db.execute(delete(DepositAddress).where(DepositAddress.user_id.in_(ids)))
        await db.execute(delete(Wallet).where(Wallet.user_id.in_(ids)))
        await db.execute(delete(Outbox).where(Outbox.chat_id >= DEMO_BASE))
        await db.execute(delete(User).where(User.user_id.in_(ids)))
        await db.execute(delete(AuditLog).where(AuditLog.details["demo"].astext == "true"))
    print(f"removed {len(ids)} demo users and their data")


def _blocks_around(tz: str, now: dt.datetime) -> list[tuple[int, int]]:
    hour = timeutil.to_local(now, tz).hour
    cur = hour // 2 * 2
    return [((cur + d) % 24, (cur + d + 2) % 24) for d in (-2, 0, 2)]


async def seed_demo(purge_only: bool = False) -> int:
    settings = get_settings()
    if settings.environment == "production":
        print("❌ refusing to seed demo data while ENVIRONMENT=production")
        return 1
    await purge()
    if purge_only:
        await dispose_engine()
        return 0

    rng = random.Random(42)
    now = timeutil.utcnow()
    ids: dict[str, list[int]] = {"sellers": [], "scanners": []}
    tg = iter(range(DEMO_BASE + 1, DEMO_BASE + 1000))

    # ── people ──────────────────────────────────────────────────────────────
    async with session_scope() as db:
        for name, country, tz in SELLERS:
            u = User(telegram_id=next(tg), username=name.split()[0].lower() + "_s", name=name, role="seller", status="approved",
                     country=country, timezone=tz, approved_at=now - dt.timedelta(days=rng.randint(5, 30)))
            db.add(u)
            await db.flush()
            await wallet.ensure_wallets(db, [u.user_id])
            ids["sellers"].append(u.user_id)
        for name, country, tz, alias, rep, slot_list in SCANNERS:
            u = User(telegram_id=next(tg), username=name.split()[0].lower() + "_sc", name=name, role="scanner", status="approved",
                     country=country, timezone=tz, alias=alias, reputation=rep, approved_at=now - dt.timedelta(days=rng.randint(10, 40)))
            db.add(u)
            await db.flush()
            await wallet.ensure_wallets(db, [u.user_id])
            blocks = set(slot_list)
            if alias in ("user1", "user3", "user6"):  # make sure some scanners are live right now
                blocks |= set(_blocks_around(tz, now))
            for start, end in sorted(blocks):
                db.add(ScannerSlot(user_id=u.user_id, name=alias, slot_start=start, slot_end=end, timezone=tz, reputation=rep))
            ids["scanners"].append(u.user_id)
        # people the admin still has to look at
        for name, role, country, tz, status in [
            ("Tariq Aziz", "scanner", "PK", "Asia/Karachi", "pending"),
            ("Mei Lin", "scanner", "MY", "Asia/Kuala_Lumpur", "pending"),
            ("Jack Brown", "seller", "AU", "Australia/Sydney", "pending"),
            ("Ravi Kumar", "scanner", "IN", "Asia/Kolkata", "approved"),  # approved, no name yet
            ("Blocked Bob", "seller", "RU", "Europe/Moscow", "suspended"),
        ]:
            u = User(telegram_id=next(tg), username=name.split()[0].lower(), name=name, role=role, status=status, country=country, timezone=tz,
                     approved_at=now - dt.timedelta(days=3) if status != "pending" else None)
            db.add(u)
            await db.flush()
            await wallet.ensure_wallets(db, [u.user_id])
            if role == "scanner" and status == "approved":
                for start, end in ((8, 10), (10, 12)):
                    db.add(ScannerSlot(user_id=u.user_id, name=None, slot_start=start, slot_end=end, timezone=tz))

    # ── deposits ────────────────────────────────────────────────────────────
    async with session_scope() as db:
        for i, seller_id in enumerate(ids["sellers"]):
            for k in range(rng.randint(1, 2)):
                await payments.credit_onchain_deposit(
                    db, user_id=seller_id, amount=Decimal(rng.choice([25, 40, 60, 100])), tx_hash=f"0xdemo{i:02d}{k}" + "a" * 56,
                    log_index=0, address="0x" + "d" * 40, block_number=1_000_000 + i, now=now - dt.timedelta(days=rng.randint(8, 20)),
                )
        small = await payments.credit_onchain_deposit(
            db, user_id=ids["sellers"][0], amount=Decimal("0.4"), tx_hash="0xdemobelowmin" + "b" * 50, log_index=0, address="0x" + "d" * 40, block_number=1_000_100
        )
        assert small is not None
        for i, (seller_id, amount) in enumerate(((ids["sellers"][1], "15"), (ids["sellers"][3], "30"))):
            user = await users.require_user(db, seller_id)
            await payments.create_binance_claim(db, user, Decimal(amount), f"M_P_DEMO{i:06d}")

    # ── historic tasks (last 14 days) ───────────────────────────────────────
    scanner_slots: dict[int, list[ScannerSlot]] = {}
    async with session_scope() as db:
        for sid in ids["scanners"]:
            scanner_slots[sid] = list((await db.execute(select(ScannerSlot).where(ScannerSlot.user_id == sid))).scalars())

    outcomes = ["confirmed"] * 38 + ["skipped"] * 4 + ["expired"] * 4 + ["timeout"] * 2 + ["dispute_pay"] * 3 + ["dispute_refund"] * 2
    rng.shuffle(outcomes)
    counter = 0
    open_dispute_proof_id: int | None = None
    for outcome in outcomes:
        counter += 1
        scanner_id = rng.choice(ids["scanners"])
        seller_id = rng.choice(ids["sellers"])
        slot = rng.choice(scanner_slots[scanner_id])
        day_back = rng.choice([0, 0, 0] + list(range(1, 15)))  # a few tasks today so the dashboard has live numbers
        local_date = (timeutil.to_local(now, slot.timezone) - dt.timedelta(days=day_back)).date()
        start, _ = timeutil.occurrence_bounds(slot.slot_start, slot.slot_end, slot.timezone, local_date)
        t0 = start + dt.timedelta(minutes=rng.randint(5, 50))
        if t0 > now - dt.timedelta(minutes=90):
            continue
        async with session_scope() as db:
            seller = await users.require_user(db, seller_id)
            try:
                async with db.begin_nested():  # a refused task leaves no trace
                    s = await sessions.create_session(db, seller, scanner_id, URL.format(n=counter), now=t0)
            except (sessions.SessionError, wallet.WalletError):  # not enough funds / scanner busy: skip this one
                continue
            sid = s.session_id
            await db.execute(update(TaskSession).where(TaskSession.session_id == sid).values(created_at=t0))
            if outcome == "skipped":
                await sessions.skip(db, sid, scanner_id, now=t0 + dt.timedelta(seconds=25))
            elif outcome == "expired":
                await sessions.process_expire(db, sid, t0 + dt.timedelta(minutes=3))
            else:
                await sessions.accept(db, sid, scanner_id, now=t0 + dt.timedelta(seconds=40))
                if outcome == "timeout":
                    await sessions.process_task_timeout(db, sid, t0 + dt.timedelta(minutes=45))
                else:
                    await sessions.mark_done(db, sid, scanner_id, now=t0 + dt.timedelta(minutes=rng.randint(3, 8)))
                    await sessions.process_prompt(db, sid, t0 + dt.timedelta(minutes=12))
                    if outcome == "confirmed":
                        await sessions.confirm(db, sid, seller_id, now=t0 + dt.timedelta(minutes=rng.randint(13, 25)))
                    else:
                        _, dispute = await sessions.reject(db, sid, seller_id, now=t0 + dt.timedelta(minutes=14))
                        rel = proofs.save_proof(mock_screenshot("Payment successful", ok=outcome == "dispute_pay"), dispute.id)
                        await disputes.submit_proof(db, dispute.id, scanner_id, proof_file=rel, telegram_file_id=None)
                        decision = DisputeResolution.PAY_SCANNER if outcome == "dispute_pay" else DisputeResolution.REFUND_SELLER
                        note = "Screenshot shows the success page." if outcome == "dispute_pay" else "Screenshot shows an unpaid checkout."
                        await disputes.resolve(db, dispute.id, decision, by="admin:demo", notes=note, now=t0 + dt.timedelta(minutes=40))
                        await db.execute(update(Dispute).where(Dispute.id == dispute.id).values(created_at=t0 + dt.timedelta(minutes=14)))
            await db.flush()
            await db.execute(update(LedgerEntry).where(LedgerEntry.ref_type == "session", LedgerEntry.ref_id == sid).values(created_at=t0 + dt.timedelta(minutes=15)))
            await db.execute(update(TransactionHistory).where(TransactionHistory.session_id == sid).values(created_at=t0 + dt.timedelta(minutes=15)))
        open_dispute_proof_id = open_dispute_proof_id or sid

    # ── cases that need the admin right now ─────────────────────────────────
    live_scanners = [sid for sid in ids["scanners"] if any(timeutil.active_occurrence(s.slot_start, s.slot_end, s.timezone, now) for s in scanner_slots[sid])]
    async with session_scope() as db:
        sellers = [await users.require_user(db, i) for i in ids["sellers"]]
        # 1) rejected, scanner still has to send the screenshot
        s1 = await sessions.create_session(db, sellers[0], live_scanners[0], URL.format(n=9001), now=now - dt.timedelta(minutes=25))
        await sessions.accept(db, s1.session_id, live_scanners[0], now=now - dt.timedelta(minutes=24))
        await sessions.mark_done(db, s1.session_id, live_scanners[0], now=now - dt.timedelta(minutes=20))
        await sessions.process_prompt(db, s1.session_id, now - dt.timedelta(minutes=17))
        await sessions.reject(db, s1.session_id, sellers[0].user_id, now=now - dt.timedelta(minutes=6))
        # 2) rejected + screenshot waiting for a decision (AI was unsure)
        s2 = await sessions.create_session(db, sellers[1], live_scanners[1 % len(live_scanners)], URL.format(n=9002), now=now - dt.timedelta(minutes=50))
        sc2 = s2.scanner_id
        await sessions.accept(db, s2.session_id, sc2, now=now - dt.timedelta(minutes=49))
        await sessions.mark_done(db, s2.session_id, sc2, now=now - dt.timedelta(minutes=44))
        await sessions.process_prompt(db, s2.session_id, now - dt.timedelta(minutes=41))
        _, d2 = await sessions.reject(db, s2.session_id, sellers[1].user_id, now=now - dt.timedelta(minutes=30))
        rel = proofs.save_proof(mock_screenshot("Payment pending…", ok=False), d2.id)
        await disputes.submit_proof(db, d2.id, sc2, proof_file=rel, telegram_file_id=None)
        d2_row = await db.get(Dispute, d2.id)
        d2_row.ai_status = "done"
        d2_row.ai_verdict = {"verdict": "unclear", "confidence": 0.55, "reason": "The page is partly cropped; the payment state is not visible.", "model": settings.ai_model}
        # 3) a task in progress and one waiting for the scanner to answer
        s3 = await sessions.create_session(db, sellers[2], live_scanners[-1], URL.format(n=9003), now=now - dt.timedelta(minutes=3))
        await sessions.accept(db, s3.session_id, s3.scanner_id, now=now - dt.timedelta(minutes=2))

    # ── withdrawals ─────────────────────────────────────────────────────────
    async with session_scope() as db:
        for i, scanner_id in enumerate(ids["scanners"]):
            scanner = await users.require_user(db, scanner_id)
            w = await wallet.get_wallet(db, scanner_id)
            if w.balance < 2:
                continue
            address = "0x" + f"{i + 1:040x}"
            method, target = ("bep20", address) if i % 2 == 0 else ("binance", f"2000{i}5551")
            wd = await payments.request_withdrawal(db, scanner, method, target, Decimal("1.5"))
            if i == 0:
                await payments.approve_withdrawal(db, wd.id, "admin:demo")
                await payments.complete_withdrawal(db, wd.id, "admin:demo", "0xdemopaid" + "c" * 54)
            elif i == 1:
                await payments.reject_withdrawal(db, wd.id, "admin:demo", "Address looks wrong")
            elif i == 2:
                await payments.approve_withdrawal(db, wd.id, "admin:demo")
            # the rest stay pending

    # ── odds and ends ───────────────────────────────────────────────────────
    async with session_scope() as db:
        for action, target, details in [
            ("login", None, None), ("user_approved", "user", {"demo": "true"}), ("settings_updated", "settings", {"demo": "true", "task_amount": {"from": "0.4", "to": "0.5"}}),
            ("scanner_named", "user", {"demo": "true", "alias": "user3"}), ("dispute_resolved", "dispute", {"demo": "true", "resolution": "pay_scanner"}),
        ]:
            db.add(AuditLog(admin_username="demo", action=action, target_type=target, details=details, ip="203.0.113.7"))
        broadcast = Broadcast(message="Welcome to the new payout schedule - withdrawals are processed daily.", audience="all", total=6, created_by="demo")
        db.add(broadcast)
        await db.flush()
        for i, sc in enumerate(ids["scanners"]):
            u = await users.require_user(db, sc)
            db.add(Outbox(chat_id=u.telegram_id, body="📣 demo", status="sent" if i < 5 else "failed", broadcast_id=broadcast.id, sent_at=now))
        for i, uid in enumerate(ids["sellers"] + ids["scanners"]):
            await db.execute(update(User).where(User.user_id == uid).values(created_at=now - dt.timedelta(days=rng.randint(15, 45), hours=i)))
        # nothing here must ever reach a real Telegram chat
        await db.execute(text("UPDATE outbox SET status = 'sent', sent_at = now() WHERE status = 'queued' AND chat_id >= :base").bindparams(base=DEMO_BASE))
        report = await wallet.reconcile(db)

    print(f"✅ demo data created ({len(ids['sellers'])} sellers, {len(ids['scanners'])} scanners, {counter} historic tasks)")
    print(f"   ledger reconciliation: {'OK' if report.ok else 'MISMATCH ' + str(report.problems)}")
    await dispose_engine()
    return 0 if report.ok else 1

