"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 15:26:02.843521
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('totp_secret_enc', sa.Text(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('username', name=op.f('uq_admins_username'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_created', 'audit_log', ['created_at'], unique=False)
    op.create_table('broadcasts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=10), nullable=False),
    sa.Column('total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("audience IN ('all', 'sellers', 'scanners')", name=op.f('ck_broadcasts_audience_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcasts'))
    )
    op.create_table('kv_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_kv_state'))
    )
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('parse_mode', sa.String(length=10), nullable=True),
    sa.Column('reply_markup', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disable_preview', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('broadcast_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'sent', 'failed')", name=op.f('ck_outbox_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_outbox_dedupe_key'))
    )
    op.create_index('ix_outbox_due', 'outbox', ['status', 'next_attempt_at'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('language_code', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='onboarding', nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alias', sa.String(length=32), nullable=True),
    sa.Column('reputation', sa.Integer(), server_default=sa.text('50'), nullable=False),
    sa.Column('last_assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bot_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.CheckConstraint("role IN ('seller', 'scanner')", name=op.f('ck_users_role_valid')),
    sa.CheckConstraint("status IN ('onboarding', 'pending', 'approved', 'rejected', 'suspended')", name=op.f('ck_users_status_valid')),
    sa.CheckConstraint('reputation BETWEEN 0 AND 100', name=op.f('ck_users_reputation_range')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('alias', name=op.f('uq_users_alias')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_users_telegram_id'))
    )
    op.create_index('ix_users_role_status', 'users', ['role', 'status'], unique=False)
    op.create_table('deposit_addresses',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('derivation_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_deposit_addresses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_deposit_addresses')),
    sa.UniqueConstraint('address', name=op.f('uq_deposit_addresses_address')),
    sa.UniqueConstraint('derivation_index', name=op.f('uq_deposit_addresses_derivation_index'))
    )
    op.create_table('deposits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('tx_hash', sa.String(length=100), nullable=False),
    sa.Column('log_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('credited_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("method IN ('bep20', 'binance')", name=op.f('ck_deposits_method_valid')),
    sa.CheckConstraint("status IN ('pending', 'credited', 'below_min', 'rejected')", name=op.f('ck_deposits_status_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_deposits_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deposits')),
    sa.UniqueConstraint('method', 'tx_hash', 'log_index', name='uq_deposits_tx')
    )
    op.create_index('ix_deposits_status', 'deposits', ['status'], unique=False)
    op.create_index('ix_deposits_user', 'deposits', ['user_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('entry_type', sa.String(length=24), nullable=False),
    sa.Column('balance_delta', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('pending_delta', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('pending_after', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ref_type', sa.String(length=24), nullable=True),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entry_type IN ('deposit', 'hold', 'release', 'payment', 'earning', 'commission', 'withdrawal_lock', 'withdrawal_unlock', 'withdrawal_paid', 'withdrawal_fee', 'adjustment')", name=op.f('ck_ledger_entries_type_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_ledger_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    op.create_index('ix_ledger_entries_ref', 'ledger_entries', ['ref_type', 'ref_id'], unique=False)
    op.create_index('ix_ledger_entries_user', 'ledger_entries', ['user_id', 'id'], unique=False)
    op.create_table('scanner_slots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('slot_start', sa.SmallInteger(), nullable=False),
    sa.Column('slot_end', sa.SmallInteger(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('reputation', sa.Integer(), server_default=sa.text('50'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('slot_end BETWEEN 0 AND 23', name=op.f('ck_scanner_slots_end_hour')),
    sa.CheckConstraint('slot_start BETWEEN 0 AND 23', name=op.f('ck_scanner_slots_start_hour')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_scanner_slots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scanner_slots')),
    sa.UniqueConstraint('user_id', 'slot_start', 'slot_end', name='uq_scanner_slots_user_window')
    )
    op.create_index('ix_scanner_slots_active', 'scanner_slots', ['is_active', 'timezone'], unique=False)
    op.create_index(op.f('ix_scanner_slots_user_id'), 'scanner_slots', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('pending', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('total_deposited', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('total_withdrawn', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('binance_address', sa.String(length=64), nullable=True),
    sa.Column('bep20_address', sa.String(length=42), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance >= 0', name=op.f('ck_wallets_balance_non_negative')),
    sa.CheckConstraint('pending >= 0', name=op.f('ck_wallets_pending_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_wallets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_wallets'))
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('admin_note', sa.String(length=255), nullable=True),
    sa.Column('processed_by', sa.String(length=64), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('bep20', 'binance')", name=op.f('ck_withdrawals_method_valid')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'processing', 'completed', 'rejected', 'failed')", name=op.f('ck_withdrawals_status_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_withdrawals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_withdrawals'))
    )
    op.create_index('ix_withdrawals_status', 'withdrawals', ['status'], unique=False)
    op.create_index('ix_withdrawals_user', 'withdrawals', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('scanner_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('slot_id', sa.BigInteger(), nullable=True),
    sa.Column('slot_label', sa.String(length=80), nullable=True),
    sa.Column('seller_timezone', sa.String(length=64), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_reason', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('awaiting_scanner', 'accepted', 'done', 'confirmed', 'disputed', 'refunded', 'expired', 'skipped', 'timed_out', 'cancelled')", name=op.f('ck_sessions_status_valid')),
    sa.ForeignKeyConstraint(['scanner_id'], ['users.user_id'], name=op.f('fk_sessions_scanner_id_users')),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], name=op.f('fk_sessions_seller_id_users')),
    sa.ForeignKeyConstraint(['slot_id'], ['scanner_slots.id'], name=op.f('fk_sessions_slot_id_scanner_slots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_sessions'))
    )
    op.create_index('ix_sessions_scanner_status', 'sessions', ['scanner_id', 'status'], unique=False)
    op.create_index('ix_sessions_seller_status', 'sessions', ['seller_id', 'status'], unique=False)
    op.create_index('ix_sessions_status_deadline', 'sessions', ['status', 'deadline_at'], unique=False)
    op.create_index('ix_sessions_status_expires', 'sessions', ['status', 'expires_at'], unique=False)
    op.create_table('slot_notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slot_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('occurrence_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurrence_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('response', sa.String(length=8), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("response IS NULL OR response IN ('ready', 'busy')", name=op.f('ck_slot_notifications_response_valid')),
    sa.ForeignKeyConstraint(['slot_id'], ['scanner_slots.id'], name=op.f('fk_slot_notifications_slot_id_scanner_slots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_slot_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slot_notifications')),
    sa.UniqueConstraint('slot_id', 'occurrence_start', name='uq_slot_notifications_occurrence')
    )
    op.create_index(op.f('ix_slot_notifications_user_id'), 'slot_notifications', ['user_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('raised_by', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('proof_file', sa.String(length=255), nullable=True),
    sa.Column('proof_telegram_file_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proof_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_status', sa.String(length=12), nullable=True),
    sa.Column('ai_verdict', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('awaiting_proof', 'pending_review', 'resolved', 'rejected')", name=op.f('ck_disputes_status_valid')),
    sa.ForeignKeyConstraint(['raised_by'], ['users.user_id'], name=op.f('fk_disputes_raised_by_users')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name=op.f('fk_disputes_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disputes')),
    sa.UniqueConstraint('session_id', name=op.f('uq_disputes_session_id'))
    )
    op.create_index('ix_disputes_status', 'disputes', ['status'], unique=False)
    op.create_table('transaction_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('scanner_id', sa.BigInteger(), nullable=False),
    sa.Column('scanner_name', sa.String(length=32), nullable=True),
    sa.Column('seller_name', sa.String(length=255), nullable=True),
    sa.Column('seller_country', sa.String(length=2), nullable=True),
    sa.Column('seller_timezone', sa.String(length=64), nullable=True),
    sa.Column('scanner_country', sa.String(length=2), nullable=True),
    sa.Column('scanner_timezone', sa.String(length=64), nullable=True),
    sa.Column('slot', sa.String(length=80), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('completed', 'disputed', 'refunded')", name=op.f('ck_transaction_history_status_valid')),
    sa.ForeignKeyConstraint(['scanner_id'], ['users.user_id'], name=op.f('fk_transaction_history_scanner_id_users')),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], name=op.f('fk_transaction_history_seller_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name=op.f('fk_transaction_history_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_history')),
    sa.UniqueConstraint('session_id', name=op.f('uq_transaction_history_session_id'))
    )
    op.create_index('ix_transaction_history_confirmed_at', 'transaction_history', ['confirmed_at'], unique=False)
    op.create_index('ix_transaction_history_scanner', 'transaction_history', ['scanner_id'], unique=False)
    op.create_index('ix_transaction_history_seller', 'transaction_history', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_history_seller', table_name='transaction_history')
    op.drop_index('ix_transaction_history_scanner', table_name='transaction_history')
    op.drop_index('ix_transaction_history_confirmed_at', table_name='transaction_history')
    op.drop_table('transaction_history')
    op.drop_index('ix_disputes_status', table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_slot_notifications_user_id'), table_name='slot_notifications')
    op.drop_table('slot_notifications')
    op.drop_index('ix_sessions_status_expires', table_name='sessions')
    op.drop_index('ix_sessions_status_deadline', table_name='sessions')
    op.drop_index('ix_sessions_seller_status', table_name='sessions')
    op.drop_index('ix_sessions_scanner_status', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_withdrawals_user', table_name='withdrawals')
    op.drop_index('ix_withdrawals_status', table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_scanner_slots_user_id'), table_name='scanner_slots')
    op.drop_index('ix_scanner_slots_active', table_name='scanner_slots')
    op.drop_table('scanner_slots')
    op.drop_index('ix_ledger_entries_user', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_ref', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_deposits_user', table_name='deposits')
    op.drop_index('ix_deposits_status', table_name='deposits')
    op.drop_table('deposits')
    op.drop_table('deposit_addresses')
    op.drop_index('ix_users_role_status', table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index('ix_outbox_due', table_name='outbox')
    op.drop_table('outbox')
    op.drop_table('kv_state')
    op.drop_table('broadcasts')
    op.drop_index('ix_audit_log_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('admins')
    # ### end Alembic commands ###
